"""empty message

Revision ID: 045bed4b9239
Revises: 9454937b033f
Create Date: 2022-06-07 07:53:52.673330

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '045bed4b9239'
down_revision = '9454937b033f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('episode__index__show_id', table_name='episode')
    op.create_index(op.f('ix_episode_show_id'), 'episode', ['show_id'], unique=False)
    op.drop_index('series__index_show', table_name='series')
    op.create_index(op.f('ix_series_show_id'), 'series', ['show_id'], unique=False)
    op.create_foreign_key(None, 'series', 'show', ['show_id'], ['id'])
    op.drop_constraint('show_image_fkey', 'show', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('show_image_fkey', 'show', 'image', ['image'], ['id'])
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.drop_index(op.f('ix_series_show_id'), table_name='series')
    op.create_index('series__index_show', 'series', ['show_id'], unique=False)
    op.drop_index(op.f('ix_episode_show_id'), table_name='episode')
    op.create_index('episode__index__show_id', 'episode', ['show_id'], unique=False)
    # ### end Alembic commands ###
