"""empty message

Revision ID: 101e7a93f543
Revises: b180ade3abe8
Create Date: 2022-05-17 00:14:43.048552

"""

# revision identifiers, used by Alembic.
revision = '101e7a93f543'
down_revision = 'b180ade3abe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
