"""empty message

Revision ID: 113f09b265d7
Revises: 045bed4b9239
Create Date: 2022-06-07 23:48:13.263282

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '113f09b265d7'
down_revision = '045bed4b9239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'show', 'image', ['image'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    # ### end Alembic commands ###
