"""empty message

Revision ID: 122e8848dec5
Revises: 3f5c33be9708
Create Date: 2022-06-05 04:38:11.355091

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '122e8848dec5'
down_revision = '3f5c33be9708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('show_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_series_name'), 'series', ['name'], unique=False)
    op.create_index(op.f('ix_series_show_id'), 'series', ['show_id'], unique=False)
    op.alter_column('show', 'series',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.create_index(op.f('ix_show_series'), 'show', ['series'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_series'), table_name='show')
    op.alter_column('show', 'series',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_index(op.f('ix_series_show_id'), table_name='series')
    op.drop_index(op.f('ix_series_name'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
