"""empty message

Revision ID: 290423aa2205
Revises: b3dfb5b835f3
Create Date: 2022-06-06 18:35:39.495541

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '290423aa2205'
down_revision = 'b3dfb5b835f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('streaming_options', sqlmodel.sql.sqltypes.AutoString(),default="000000", nullable=True))
    op.create_index(op.f('ix_show_streaming_options'), 'show', ['streaming_options'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_streaming_options'), table_name='show')
    op.drop_column('show', 'streaming_options')
    # ### end Alembic commands ###
