"""empty message

Revision ID: 2d493d1c703e
Revises: c93e16794e43
Create Date: 2022-05-21 23:12:35.647255

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '2d493d1c703e'
down_revision = 'c93e16794e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('feed_file_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_show_feed_file_link'), 'show', ['feed_file_link'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_feed_file_link'), table_name='show')
    op.drop_column('show', 'feed_file_link')
    # ### end Alembic commands ###
