"""empty message

Revision ID: 3a107ea8a7be
Revises: 786afc282a4a
Create Date: 2022-05-14 18:14:49.771570

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '3a107ea8a7be'
down_revision = '786afc282a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
