"""empty message

Revision ID: 3f5c33be9708
Revises: 9fdee7133f40
Create Date: 2022-06-04 01:10:54.565728

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f5c33be9708'
down_revision = '9fdee7133f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accesstoken_created_at', table_name='accesstoken')
    op.drop_table('accesstoken')
    op.alter_column('show', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_table('accesstoken',
    sa.Column('token', sa.VARCHAR(length=43), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='accesstoken_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name='accesstoken_pkey')
    )
    op.create_index('ix_accesstoken_created_at', 'accesstoken', ['created_at'], unique=False)
    # ### end Alembic commands ###
