"""empty message

Revision ID: 51964db740c1
Revises: 
Create Date: 2022-05-14 19:20:58.333764

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '51964db740c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_file_url'), 'image', ['file_url'], unique=False)
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.create_index(op.f('ix_image_is_removed'), 'image', ['is_removed'], unique=False)
    op.create_index(op.f('ix_image_title'), 'image', ['title'], unique=False)
    op.create_table('show',
    sa.Column('language', sa.Enum('english', name='language'), nullable=True),
    sa.Column('category', sa.Enum('arts_books', name='category'), nullable=True),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('show_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('show_copyright', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_build_date', sa.DateTime(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('podcast_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['image'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_description'), 'show', ['description'], unique=False)
    op.create_index(op.f('ix_show_generator'), 'show', ['generator'], unique=False)
    op.create_index(op.f('ix_show_id'), 'show', ['id'], unique=False)
    op.create_index(op.f('ix_show_image'), 'show', ['image'], unique=False)
    op.create_index(op.f('ix_show_is_locked'), 'show', ['is_locked'], unique=False)
    op.create_index(op.f('ix_show_is_removed'), 'show', ['is_removed'], unique=False)
    op.create_index(op.f('ix_show_last_build_date'), 'show', ['last_build_date'], unique=False)
    op.create_index(op.f('ix_show_media_link'), 'show', ['media_link'], unique=False)
    op.create_index(op.f('ix_show_podcast_owner'), 'show', ['podcast_owner'], unique=False)
    op.create_index(op.f('ix_show_show_copyright'), 'show', ['show_copyright'], unique=False)
    op.create_index(op.f('ix_show_show_link'), 'show', ['show_link'], unique=False)
    op.create_index(op.f('ix_show_title'), 'show', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', fastapi_users_db_sqlalchemy.guid.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('accesstoken',
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_accesstoken_created_at'), 'accesstoken', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accesstoken_created_at'), table_name='accesstoken')
    op.drop_table('accesstoken')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_show_title'), table_name='show')
    op.drop_index(op.f('ix_show_show_link'), table_name='show')
    op.drop_index(op.f('ix_show_show_copyright'), table_name='show')
    op.drop_index(op.f('ix_show_podcast_owner'), table_name='show')
    op.drop_index(op.f('ix_show_media_link'), table_name='show')
    op.drop_index(op.f('ix_show_last_build_date'), table_name='show')
    op.drop_index(op.f('ix_show_is_removed'), table_name='show')
    op.drop_index(op.f('ix_show_is_locked'), table_name='show')
    op.drop_index(op.f('ix_show_image'), table_name='show')
    op.drop_index(op.f('ix_show_id'), table_name='show')
    op.drop_index(op.f('ix_show_generator'), table_name='show')
    op.drop_index(op.f('ix_show_description'), table_name='show')
    op.drop_table('show')
    op.drop_index(op.f('ix_image_title'), table_name='image')
    op.drop_index(op.f('ix_image_is_removed'), table_name='image')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_index(op.f('ix_image_file_url'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
