"""empty message

Revision ID: 5364aed7fa2f
Revises: 9f27bcfd53de
Create Date: 2022-05-21 20:27:37.796575

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '5364aed7fa2f'
down_revision = '9f27bcfd53de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
