"""empty message

Revision ID: 5a4ab2483069
Revises: 113f09b265d7
Create Date: 2022-06-08 00:50:40.365660

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '5a4ab2483069'
down_revision = '113f09b265d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_show_image'), 'show', ['image'], unique=False)
    op.create_index(op.f('ix_show_owner'), 'show', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_owner'), table_name='show')
    op.drop_index(op.f('ix_show_image'), table_name='show')
    # ### end Alembic commands ###
