"""empty message

Revision ID: 786afc282a4a
Revises: 617f2548b6db
Create Date: 2022-05-14 18:13:42.133020

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '786afc282a4a'
down_revision = '617f2548b6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
