"""empty message

Revision ID: 7bf2d0cb62f0
Revises: 101e7a93f543
Create Date: 2022-05-20 00:06:21.483844

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '7bf2d0cb62f0'
down_revision = '101e7a93f543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_episode_cover_image_link', table_name='episode')
    op.drop_index('ix_episode_description', table_name='episode')
    op.drop_index('ix_episode_duration', table_name='episode')
    op.drop_index('ix_episode_episode_guid', table_name='episode')
    op.drop_index('ix_episode_episode_link', table_name='episode')
    op.drop_index('ix_episode_episode_num', table_name='episode')
    op.drop_index('ix_episode_explicit', table_name='episode')
    op.drop_index('ix_episode_file_link', table_name='episode')
    op.drop_index('ix_episode_id', table_name='episode')
    op.drop_index('ix_episode_is_removed', table_name='episode')
    op.drop_index('ix_episode_pub_date', table_name='episode')
    op.drop_index('ix_episode_season_num', table_name='episode')
    op.drop_index('ix_episode_title', table_name='episode')
    op.drop_table('episode')
    op.drop_index('ix_show_description', table_name='show')
    op.drop_index('ix_show_generator', table_name='show')
    op.drop_index('ix_show_id', table_name='show')
    op.drop_index('ix_show_image', table_name='show')
    op.drop_index('ix_show_is_locked', table_name='show')
    op.drop_index('ix_show_is_removed', table_name='show')
    op.drop_index('ix_show_last_build_date', table_name='show')
    op.drop_index('ix_show_media_link', table_name='show')
    op.drop_index('ix_show_podcast_owner', table_name='show')
    op.drop_index('ix_show_show_copyright', table_name='show')
    op.drop_index('ix_show_show_link', table_name='show')
    op.drop_index('ix_show_title', table_name='show')
    op.drop_table('show')
    op.drop_index('ix_image_file_url', table_name='image')
    op.drop_index('ix_image_id', table_name='image')
    op.drop_index('ix_image_is_removed', table_name='image')
    op.drop_index('ix_image_title', table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('is_removed', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('file_url', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_image_title', 'image', ['title'], unique=False)
    op.create_index('ix_image_is_removed', 'image', ['is_removed'], unique=False)
    op.create_index('ix_image_id', 'image', ['id'], unique=False)
    op.create_index('ix_image_file_url', 'image', ['file_url'], unique=False)
    op.create_table('show',
    sa.Column('language', sa.VARCHAR(length=7), nullable=True),
    sa.Column('category', sa.VARCHAR(length=10), nullable=True),
    sa.Column('is_removed', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('show_link', sa.VARCHAR(), nullable=False),
    sa.Column('media_link', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('generator', sa.VARCHAR(), nullable=False),
    sa.Column('show_copyright', sa.VARCHAR(), nullable=False),
    sa.Column('last_build_date', sa.DATETIME(), nullable=False),
    sa.Column('image', sa.CHAR(length=32), nullable=True),
    sa.Column('podcast_owner', sa.VARCHAR(), nullable=False),
    sa.Column('is_locked', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['image'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_show_title', 'show', ['title'], unique=False)
    op.create_index('ix_show_show_link', 'show', ['show_link'], unique=False)
    op.create_index('ix_show_show_copyright', 'show', ['show_copyright'], unique=False)
    op.create_index('ix_show_podcast_owner', 'show', ['podcast_owner'], unique=False)
    op.create_index('ix_show_media_link', 'show', ['media_link'], unique=False)
    op.create_index('ix_show_last_build_date', 'show', ['last_build_date'], unique=False)
    op.create_index('ix_show_is_removed', 'show', ['is_removed'], unique=False)
    op.create_index('ix_show_is_locked', 'show', ['is_locked'], unique=False)
    op.create_index('ix_show_image', 'show', ['image'], unique=False)
    op.create_index('ix_show_id', 'show', ['id'], unique=False)
    op.create_index('ix_show_generator', 'show', ['generator'], unique=False)
    op.create_index('ix_show_description', 'show', ['description'], unique=False)
    op.create_table('episode',
    sa.Column('episode_type', sa.VARCHAR(length=4), nullable=True),
    sa.Column('is_removed', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('episode_link', sa.VARCHAR(), nullable=False),
    sa.Column('file_link', sa.VARCHAR(), nullable=False),
    sa.Column('cover_image_link', sa.VARCHAR(), nullable=False),
    sa.Column('episode_guid', sa.VARCHAR(), nullable=False),
    sa.Column('episode_num', sa.INTEGER(), nullable=False),
    sa.Column('season_num', sa.INTEGER(), nullable=False),
    sa.Column('explicit', sa.BOOLEAN(), nullable=False),
    sa.Column('pub_date', sa.DATETIME(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_episode_title', 'episode', ['title'], unique=False)
    op.create_index('ix_episode_season_num', 'episode', ['season_num'], unique=False)
    op.create_index('ix_episode_pub_date', 'episode', ['pub_date'], unique=False)
    op.create_index('ix_episode_is_removed', 'episode', ['is_removed'], unique=False)
    op.create_index('ix_episode_id', 'episode', ['id'], unique=False)
    op.create_index('ix_episode_file_link', 'episode', ['file_link'], unique=False)
    op.create_index('ix_episode_explicit', 'episode', ['explicit'], unique=False)
    op.create_index('ix_episode_episode_num', 'episode', ['episode_num'], unique=False)
    op.create_index('ix_episode_episode_link', 'episode', ['episode_link'], unique=False)
    op.create_index('ix_episode_episode_guid', 'episode', ['episode_guid'], unique=False)
    op.create_index('ix_episode_duration', 'episode', ['duration'], unique=False)
    op.create_index('ix_episode_description', 'episode', ['description'], unique=False)
    op.create_index('ix_episode_cover_image_link', 'episode', ['cover_image_link'], unique=False)
    # ### end Alembic commands ###
