"""empty message

Revision ID: 8233960d9157
Revises: 122e8848dec5
Create Date: 2022-06-05 05:05:10.163910

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8233960d9157'
down_revision = '122e8848dec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_show_series', table_name='show')
    op.drop_column('show', 'series')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('series', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.create_index('ix_show_series', 'show', ['series'], unique=False)
    # ### end Alembic commands ###
