"""empty message

Revision ID: 8a6b2dda4a1a
Revises: 8013ccc8e0af
Create Date: 2022-05-21 14:36:31.602338

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '8a6b2dda4a1a'
down_revision = '8013ccc8e0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
