"""empty message

Revision ID: 9454937b033f
Revises: 
Create Date: 2022-06-07 04:16:06.949137

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9454937b033f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_removed', sa.BOOLEAN(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_removed', sa.BOOLEAN(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('show_id', postgresql.UUID(as_uuid=True), nullable=True, foreign_key='show.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('show',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_removed', sa.BOOLEAN(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('language', sa.Enum('english', name='language'), nullable=True),
    sa.Column('show_copyright', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('arts_books', name='category'), nullable=True),
    sa.Column('show_link', sa.String(), nullable=True),
    sa.Column('media_link', sa.String(), nullable=True),
    sa.Column('generator', sa.String(), nullable=True),
    sa.Column('featured', sa.BOOLEAN(), nullable=True),
    sa.Column('image', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_locked', sa.BOOLEAN(), nullable=True),
    sa.Column('owner', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('last_build_date', sa.DateTime(), nullable=True),
    sa.Column('feed_file_link', sa.String(), nullable=True),
    sa.Column('streaming_options', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['image'], ['image.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_removed', sa.BOOLEAN(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('episode_num', sa.Integer(), nullable=True),
    sa.Column('season_num', sa.Integer(), nullable=True),
    sa.Column('explicit', sa.BOOLEAN(), nullable=True),
    sa.Column('episode_type', sa.Enum('full', name='episodetype'), nullable=True),
    sa.Column('show_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('file_link', sa.String(), nullable=True),
    sa.Column('episode_link', sa.String(), nullable=True),
    sa.Column('episode_guid', sa.String(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('cover_image', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['cover_image'], ['image.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episode')
    op.drop_table('show')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('series')
    op.drop_table('image')
    # ### end Alembic commands ###
