"""empty message

Revision ID: 9c6033895bfc
Revises: 51964db740c1
Create Date: 2022-05-14 19:22:00.024957

"""

# revision identifiers, used by Alembic.
revision = '9c6033895bfc'
down_revision = '51964db740c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
