"""empty message

Revision ID: 9f27bcfd53de
Revises: 
Create Date: 2022-05-21 16:12:19.012121

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '9f27bcfd53de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
                    sa.Column('is_removed', sa.Boolean(), nullable=False),
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_image_file_url'), 'image', ['file_url'], unique=False)
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.create_index(op.f('ix_image_is_removed'), 'image', ['is_removed'], unique=False)
    op.create_index(op.f('ix_image_title'), 'image', ['title'], unique=False)
    op.create_table('show',
                    sa.Column('language', sa.Enum('english', name='language'), nullable=True),
                    sa.Column('category', sa.Enum('arts_books', name='category'), nullable=True),
                    sa.Column('is_removed', sa.Boolean(), nullable=False),
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('show_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('media_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('generator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('show_copyright', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('last_build_date', sa.DateTime(), nullable=False),
                    sa.Column('image', sqlmodel.sql.sqltypes.GUID(), nullable=True),
                    sa.Column('podcast_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('is_locked', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['image'], ['image.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_show_description'), 'show', ['description'], unique=False)
    op.create_index(op.f('ix_show_generator'), 'show', ['generator'], unique=False)
    op.create_index(op.f('ix_show_id'), 'show', ['id'], unique=False)
    op.create_index(op.f('ix_show_image'), 'show', ['image'], unique=False)
    op.create_index(op.f('ix_show_is_locked'), 'show', ['is_locked'], unique=False)
    op.create_index(op.f('ix_show_is_removed'), 'show', ['is_removed'], unique=False)
    op.create_index(op.f('ix_show_last_build_date'), 'show', ['last_build_date'], unique=False)
    op.create_index(op.f('ix_show_media_link'), 'show', ['media_link'], unique=False)
    op.create_index(op.f('ix_show_podcast_owner'), 'show', ['podcast_owner'], unique=False)
    op.create_index(op.f('ix_show_show_copyright'), 'show', ['show_copyright'], unique=False)
    op.create_index(op.f('ix_show_show_link'), 'show', ['show_link'], unique=False)
    op.create_index(op.f('ix_show_title'), 'show', ['title'], unique=False)
    op.create_table('episode',
                    sa.Column('episode_type', sa.Enum('full', name='episodetype'), nullable=True),
                    sa.Column('is_removed', sa.Boolean(), nullable=False),
                    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('episode_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('file_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('cover_image_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('episode_guid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('episode_num', sa.Integer(), nullable=False),
                    sa.Column('season_num', sa.Integer(), nullable=False),
                    sa.Column('explicit', sa.Boolean(), nullable=False),
                    sa.Column('pub_date', sa.DateTime(), nullable=False),
                    sa.Column('duration', sa.Integer(), nullable=False),
                    sa.Column('show_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
                    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_episode_cover_image_link'), 'episode', ['cover_image_link'], unique=False)
    op.create_index(op.f('ix_episode_description'), 'episode', ['description'], unique=False)
    op.create_index(op.f('ix_episode_duration'), 'episode', ['duration'], unique=False)
    op.create_index(op.f('ix_episode_episode_guid'), 'episode', ['episode_guid'], unique=False)
    op.create_index(op.f('ix_episode_episode_link'), 'episode', ['episode_link'], unique=False)
    op.create_index(op.f('ix_episode_episode_num'), 'episode', ['episode_num'], unique=False)
    op.create_index(op.f('ix_episode_explicit'), 'episode', ['explicit'], unique=False)
    op.create_index(op.f('ix_episode_file_link'), 'episode', ['file_link'], unique=False)
    op.create_index(op.f('ix_episode_id'), 'episode', ['id'], unique=False)
    op.create_index(op.f('ix_episode_is_removed'), 'episode', ['is_removed'], unique=False)
    op.create_index(op.f('ix_episode_pub_date'), 'episode', ['pub_date'], unique=False)
    op.create_index(op.f('ix_episode_season_num'), 'episode', ['season_num'], unique=False)
    op.create_index(op.f('ix_episode_series'), 'episode', ['series'], unique=False)
    op.create_index(op.f('ix_episode_show_id'), 'episode', ['show_id'], unique=False)
    op.create_index(op.f('ix_episode_title'), 'episode', ['title'], unique=False)
    op.create_table('user',
                    sa.Column('id', fastapi_users_db_sqlalchemy.guid.GUID(), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('accesstoken',
                    sa.Column('token', sa.String(length=43), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('user_id', fastapi_users_db_sqlalchemy.guid.GUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
                    sa.PrimaryKeyConstraint('token')
                    )
    op.create_index(op.f('ix_accesstoken_created_at'), 'accesstoken', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accesstoken_created_at'), table_name='accesstoken')
    op.drop_table('accesstoken')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_episode_title'), table_name='episode')
    op.drop_index(op.f('ix_episode_show_id'), table_name='episode')
    op.drop_index(op.f('ix_episode_series'), table_name='episode')
    op.drop_index(op.f('ix_episode_season_num'), table_name='episode')
    op.drop_index(op.f('ix_episode_pub_date'), table_name='episode')
    op.drop_index(op.f('ix_episode_is_removed'), table_name='episode')
    op.drop_index(op.f('ix_episode_id'), table_name='episode')
    op.drop_index(op.f('ix_episode_file_link'), table_name='episode')
    op.drop_index(op.f('ix_episode_explicit'), table_name='episode')
    op.drop_index(op.f('ix_episode_episode_num'), table_name='episode')
    op.drop_index(op.f('ix_episode_episode_link'), table_name='episode')
    op.drop_index(op.f('ix_episode_episode_guid'), table_name='episode')
    op.drop_index(op.f('ix_episode_duration'), table_name='episode')
    op.drop_index(op.f('ix_episode_description'), table_name='episode')
    op.drop_index(op.f('ix_episode_cover_image_link'), table_name='episode')
    op.drop_table('episode')
    op.drop_index(op.f('ix_show_title'), table_name='show')
    op.drop_index(op.f('ix_show_show_link'), table_name='show')
    op.drop_index(op.f('ix_show_show_copyright'), table_name='show')
    op.drop_index(op.f('ix_show_podcast_owner'), table_name='show')
    op.drop_index(op.f('ix_show_media_link'), table_name='show')
    op.drop_index(op.f('ix_show_last_build_date'), table_name='show')
    op.drop_index(op.f('ix_show_is_removed'), table_name='show')
    op.drop_index(op.f('ix_show_is_locked'), table_name='show')
    op.drop_index(op.f('ix_show_image'), table_name='show')
    op.drop_index(op.f('ix_show_id'), table_name='show')
    op.drop_index(op.f('ix_show_generator'), table_name='show')
    op.drop_index(op.f('ix_show_description'), table_name='show')
    op.drop_table('show')
    op.drop_index(op.f('ix_image_title'), table_name='image')
    op.drop_index(op.f('ix_image_is_removed'), table_name='image')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_index(op.f('ix_image_file_url'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
