"""empty message

Revision ID: 9fdee7133f40
Revises: d18a17564ac6
Create Date: 2022-06-01 18:56:18.798500

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fdee7133f40'
down_revision = 'd18a17564ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'owner',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'show', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.alter_column('show', 'owner',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
