"""empty message

Revision ID: 9ffa75df0631
Revises: d2a6b1c7eed0
Create Date: 2022-05-16 23:44:38.386005

"""

# revision identifiers, used by Alembic.
revision = '9ffa75df0631'
down_revision = 'd2a6b1c7eed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
