"""empty message

Revision ID: b180ade3abe8
Revises: 9ffa75df0631
Create Date: 2022-05-16 23:49:16.536166

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b180ade3abe8'
down_revision = '9ffa75df0631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode',
                    sa.Column('episode_type', sa.Enum('full', name='episodetype'), nullable=True),
                    sa.Column('is_removed', sa.Boolean(), nullable=False),
                    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('episode_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('file_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('cover_image_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('episode_guid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('episode_num', sa.Integer(), nullable=False),
                    sa.Column('season_num', sa.Integer(), nullable=False),
                    sa.Column('explicit', sa.Boolean(), nullable=False),
                    sa.Column('pub_date', sa.DateTime(), nullable=False),
                    sa.Column('duration', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_episode_cover_image_link'), 'episode', ['cover_image_link'], unique=False)
    op.create_index(op.f('ix_episode_description'), 'episode', ['description'], unique=False)
    op.create_index(op.f('ix_episode_duration'), 'episode', ['duration'], unique=False)
    op.create_index(op.f('ix_episode_episode_guid'), 'episode', ['episode_guid'], unique=False)
    op.create_index(op.f('ix_episode_episode_link'), 'episode', ['episode_link'], unique=False)
    op.create_index(op.f('ix_episode_episode_num'), 'episode', ['episode_num'], unique=False)
    op.create_index(op.f('ix_episode_explicit'), 'episode', ['explicit'], unique=False)
    op.create_index(op.f('ix_episode_file_link'), 'episode', ['file_link'], unique=False)
    op.create_index(op.f('ix_episode_id'), 'episode', ['id'], unique=False)
    op.create_index(op.f('ix_episode_is_removed'), 'episode', ['is_removed'], unique=False)
    op.create_index(op.f('ix_episode_pub_date'), 'episode', ['pub_date'], unique=False)
    op.create_index(op.f('ix_episode_season_num'), 'episode', ['season_num'], unique=False)
    op.create_index(op.f('ix_episode_title'), 'episode', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_title'), table_name='episode')
    op.drop_index(op.f('ix_episode_season_num'), table_name='episode')
    op.drop_index(op.f('ix_episode_pub_date'), table_name='episode')
    op.drop_index(op.f('ix_episode_is_removed'), table_name='episode')
    op.drop_index(op.f('ix_episode_id'), table_name='episode')
    op.drop_index(op.f('ix_episode_file_link'), table_name='episode')
    op.drop_index(op.f('ix_episode_explicit'), table_name='episode')
    op.drop_index(op.f('ix_episode_episode_num'), table_name='episode')
    op.drop_index(op.f('ix_episode_episode_link'), table_name='episode')
    op.drop_index(op.f('ix_episode_episode_guid'), table_name='episode')
    op.drop_index(op.f('ix_episode_duration'), table_name='episode')
    op.drop_index(op.f('ix_episode_description'), table_name='episode')
    op.drop_index(op.f('ix_episode_cover_image_link'), table_name='episode')
    op.drop_table('episode')
    # ### end Alembic commands ###
