"""empty message

Revision ID: b3dfb5b835f3
Revises: 8233960d9157
Create Date: 2022-06-05 06:35:21.199432

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'b3dfb5b835f3'
down_revision = '8233960d9157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.drop_column('series', 'id')
    # ### end Alembic commands ###
