"""empty message

Revision ID: b6cdd24b23fc
Revises: 7bf2d0cb62f0
Create Date: 2022-05-20 00:26:03.167208

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'b6cdd24b23fc'
down_revision = '7bf2d0cb62f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
