"""empty message

Revision ID: d2a6b1c7eed0
Revises: 9c6033895bfc
Create Date: 2022-05-16 23:43:08.875723

"""

# revision identifiers, used by Alembic.
revision = 'd2a6b1c7eed0'
down_revision = '9c6033895bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
