"""empty message

Revision ID: ebea5c8b60c7
Revises: 5364aed7fa2f
Create Date: 2022-05-21 22:13:21.985606

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'ebea5c8b60c7'
down_revision = '5364aed7fa2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_show_series'), 'show', ['series'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_series'), table_name='show')
    op.drop_column('show', 'series')
    # ### end Alembic commands ###
